### ISSUE TITLE
[SUB-TASK/DEV-75] 회원 가입 시, 이미 다른 사용자가 쓰고 있는 닉네임은 쓸 수 없다

### ISSUE THREAD

**Issue by dayeon-alert** [CalenDev/calendev#14]
## Branch
`DEV-2/DEV-3/DEV-75`

## Description
회원 가입 시, 이미 다른 사용자가 쓰고 있는 닉네임은 쓸 수 없다.

## Tasks
- [x] JSON을 이용한 가짜 데이터를 생성해 이를 통해 중복 닉네임을 확인한다.
- [x] 중복을 확인하는 버튼 컴포넌트를 추가한다. 
- [x] 버튼을 클릭한 뒤, 반환되는 리턴 값이 음수일 경우 오류로 간주하고 해당 값에 대응하는 오류 메세지를 출력한다.
