### ISSUE TITLE
[ISSUE] JWT 관련 서비스 로직 수정 및 유저 roleCode 를 위한 enum 객체 추가

### ISSUE THREAD

**Issue by ekgns33** [CalenDev/calendev#31]
## Branch
`DEV-54`

## Description
*JWT 관련 서비스 로직 수정 및 유저 roleCode 를 위한 enum 객체 추가*

- jwt 토큰 자체는 탈취 시 decode가 가능하여 payload를 누구나 확인할 수 있다는 점에서 기존 로직 변경의 필요성을 느낌
  - payload에 유저 이메일을 넣는 방식에서 로그인 시 유저 이메일을 해시하여 request body에 넣어 반환하고 이를 클라이언트에서 관리.
  - userEmail이 필요한 서비스의 경우 클라이언트가 요청에 해시된 이메일을 담아서 요청하도록 로직 변경
- 유저 roleCode를 관리하기 위한 enum 객체 추가 생성 

## Tasks
- [ ] jwt payload에서 email 제거
- [ ] 기존 서비스 로직에서 email을 받는 방법 수정
- [ ]  유저 roldeCode 객체 생성

## Additional context
*작업에 대한 기타 참고 내용이나 스크린샷을 추가합니다.*
